### ISSUE TITLE
Chỉnh sửa một số định dạng

### ISSUE THREAD

**Issue by Silverbullet069** [leduyquang753/uet-graduation-latex#1]
Có một số định dạng mình thấy chưa ổn lắm:
- Indent Preamble đang là 0, cần phải để là 1cm.
- Font-size của Preamble đang là 12pt, phải thay bằng 13pt.
- Bottom margin có phải đang để 2 cm không? 
- Mình chưa thấy set line spacing = 1.3
- Cần set image directory.

https://uet.vnu.edu.vn/wp-content/uploads/2017/07/Quy-định-về-trình-bày-khóa-luận-tốt-nghiệpCLC.pdf

**Comment by leduyquang753** [comment]
Mình xem trong yêu cầu thì tóm tắt để cỡ 12 và không căn lề, còn giãn dòng thì đúng là mình chưa để ý.

**Comment by Silverbullet069** [comment]
> Mình xem trong yêu cầu thì tóm tắt để cỡ 12 và không căn lề

À ừ tóm tắt nó buộc phải là 12pt. Không hiểu sao mình gom luôn mấy cái lời cảm ơn với lời cam đoan trước vào để bắt tóm tắt cũng phải là 13pt + căn lề luôn :))
 
> 3 cm nhưng số trang thì cách 1 cm ở phía dưới. Trong code thì `footskip` ăn vào margin nên margin dưới được xác định là 2 cm.
Giờ mình hiểu rồi, bảo sao cứ thấy nó là lạ.

> Cần set image directory.
> Bạn nói rõ hơn chút.
Cái này là convention của mình thôi, mình hay thêm tạo 1 thư mục `images` rồi `\graphicspath{{images/}}`.

**Comment by leduyquang753** [comment]
> Cái này là convention của mình thôi, mình hay thêm tạo 1 thư mục images rồi viết thêm `\graphicspath{{images/}}`.

Thế thì bạn có thể tự viết vào preamble của tệp `.tex` thôi, còn mình không muốn áp đặt khi không cần thiết.

**Comment by Silverbullet069** [comment]
@leduyquang753 À tiêu đề "TÓM TẮT" phải là 13pt nhé, thêm `\setfontsize{13pt}` vào đoạn preamble.
`{\centering\setfontsize{13pt}\textbf{\MakeUppercase{#1}}\par}\vspace{1cm}`

**Comment by leduyquang753** [comment]
> À tiêu đề "TÓM TẮT" phải là 13pt nhé

Ừ mình vừa xem lại thì hóa ra mình đọc nhầm cái chữ *Tóm tắt* nhỏ ở dưới, cơ mà chỉ cần chuyển lệnh đặt cỡ chữ ra sau tiêu đề thôi.

**Comment by leduyquang753** [comment]
Đã sửa lại tỉ lệ giãn dòng và kích cỡ tiêu đề các trang `preamble` (c9a4a95).
