### ISSUE TITLE
Lỗi insert table

### ISSUE THREAD

**Issue by TKhawns** [leduyquang753/uet-graduation-latex#4]
Mình đang gặp lỗi không thể sử dụng `\begin{table}` "is not recognized", "Your command was ignored." với file .cls hiện tại. Ngoài ra mình nghĩ cần thêm tự động `\listoftable` `\listoffigures` vào mục lục. Mong bạn giúp đỡ.

**Comment by leduyquang753** [comment]
Môi trường `table` chưa được implement, để mình thêm.

Còn hai lệnh đặt danh sách kia mình chủ ý để tự gọi cho linh hoạt.

**Comment by leduyquang753** [comment]
À không, bảng thì là `tabular` rồi, còn `table` chỉ là để float, thì mình chỉ thêm một môi trường float nữa thôi, nếu cần.

**Comment by TKhawns** [comment]
mình đã thử lại với `tabular` thì không còn log lỗi, nhưng có vẻ phải tự format lại các khoảng cách và `\hline` (border của các ô) vẫn không hoạt động. `\begin{table}` là form đề xuất khi insert table từ topbar của latex nên mình nghĩ khá cần thiết.

**Comment by leduyquang753** [comment]
> `\begin{table}` là form đề xuất khi insert table từ topbar của latex

Topbar ở đâu cơ nhỉ.

**Comment by TKhawns** [comment]
![image](https://github.com/leduyquang753/uet-graduation-latex/assets/89265725/0684cb55-2118-4394-a867-a715fc2af826)

form gợi ý*

**Comment by leduyquang753** [comment]
> ![image](https://private-user-images.githubusercontent.com/89265725/332702943-0684cb55-2118-4394-a867-a715fc2af826.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM2MjIsIm5iZiI6MTcxNjM2MzMyMiwicGF0aCI6Ii84OTI2NTcyNS8zMzI3MDI5NDMtMDY4NGNiNTUtMjExOC00Mzk0LWE4NjctYTcxNWZjMmFmODI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMDAxODY1YTBiZTI3MWM2NmVlZDRkOWJmODUxNGJiNjM4OGNmMzc1MGY0NjI4MDA1MTUyOWM4MTExOWQ0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oM5lrC3bJogdpyjC9J6I6CnHr3lT6TEuUWKfND2TXYk)

Cái đấy là Overleaf rồi, mình thì không dùng Overleaf. `table` chỉ là một môi trường mặc định thôi.

**Comment by TKhawns** [comment]
à ok, vì mình thấy Overleaf được sử dụng khá phổ biến. Nhưng với `tabular` mình vẫn chưa sử dụng được `\hline` để tạo được đúng định dạng bảng.

**Comment by leduyquang753** [comment]
Đã thay đổi hẳn lại hệ thống tạo kiểu đính kèm và xác định độ dày các đường chia bảng.

@TKhawns Bạn cập nhật phiên bản mới rồi đọc lại hướng dẫn nhé.
