### ISSUE TITLE
Hỏi về sửa định dạng vị trí table và figure

### ISSUE THREAD

**Issue by anhai123** [leduyquang753/uet-graduation-latex#7]
Chào bạn, mình có sửa phần code Hình và Bảng từ `{tbp}` -> `{H}`. Mục đích của mình là để cố định vị trí của bảng với hình tương ứng với vị trí insert. Mình có sử dụng {h} viết thường nhưng vị trí vẫn cứ bị float, không được cố định và sẽ có hiện tượng là bảng insert trong `subsection `nhưng không nằm trong `subsection`, mà nó float đi đâu với nhau ấy

```
\makeattachmenttype{figure}{H}{Hình}{}{%
	\vspace{0.25cm}\attachmentcaptionbox{\centering\small\attachmentcaption}%
}{lof}{\listoffigures}{Danh sách hình vẽ}

\makeattachmenttype{table}{H}{Bảng}{%
	\attachmentcaptionbox{\centering\small\textbf{\attachmentcaption}}\vspace{0.25cm}%
}{}{lot}{\listoftables}{Danh sách bảng}

```
Vấn đề mình gặp phải khi sử dụng phần sửa trên của mình là khi mình truyền tên figure vào như thế này:
`\begin{figure}{Biểu đồ ca sử dụng của hệ thống. }` thì nó đang **không nhận giá trị truyền vào và không hiển thị caption cho figure luôn, không thêm hình của mình vào lof**

Còn với table thì` \begin{table}{Đặc tả ca sử dụng “Xoá tài khoản” }`, caption **vẫn hiển thị bình thường, vẫn thêm vào lot**

Bạn có cách nào giúp mình không? Mình cảm ơn nhé.

**Comment by leduyquang753** [comment]
(Đã trao đổi riêng.) Gói `float` có xung đột với mã nguồn của mẫu, đã chỉnh sửa lại mẫu để tương thích.
